# Site settings
name: A.J. Ouzts
email: email
url: url
description: "A blog and a portfolio"
author: "author"
title: "Alonzo (A.J.) Ouzts II"
permalink: pretty
baseurl: 

# social
github:
  username: username

twitter:
  username: username