# site settings
title: A.J. Ouzts II
subtitle: Purposely Driven Ambition
email: aj.ouzts.ii@protonmail.com
description: Welcome and learn more about who I am,<br /> what drives me, and what I've done.
url: 
author:
port: 4001

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
instagram_url: 
linkedin_url: https://www.linkedin.com/in/alonzo-a-j-ouzts-ii-19048056

# build settings
markdown: kramdown

sass:
  style: compressed
